export enum EDateTimeFormat {
  FULL_DATE_TIME_DASH = 'YYYY-MM-DD HH:mm:ss',
  FULL_MONTH_YEAR = 'MM/YYYY',
  FULL_TIME_24_HOURS = 'HH:mm:ss',
  FULL_YEAR_MONTH_DAY_AND_TIME_LOCALE_JA = 'YYYY年M月d日HH:mm',
  FULL_YEAR_MONTH_DAY_DOT = 'YYYY.MM.DD',
  FULL_YEAR_MONTH_DAY_EN_DASH = 'YYYY-MM-DD',
  FULL_YEAR_MONTH_DAY_LOCALE_JA = 'YYYY年MM月DD日',
  HOUR_MINUTE_24 = 'HH:mm',
  SHORT_YEAR_MONTH_DAY_AND_TIME = 'YY/MM/DD HH:mm',
}
